# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YoonitFacefyDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  inherit! :search_paths

  # Pods for YoonitFacefyDemo
  pod 'YoonitFacefy', :path => '../../'

 # pod 'YoonitCamera'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "#{target.name}"
  end
end
