# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YoonitFacefyDemo' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for YoonitFacefyDemo
  pod 'YoonitFacefy', :path => '../../'

  pod 'YoonitCamera'
end
